version: '3'
services:  
  webapi:
    image: cherrypick/sarenza
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
        - 5500:80
        - 5501:443
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
